CREATE TABLE books (
    id INTEGER PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    chapter_count INTEGER NOT NULL,
    testament TEXT NOT NULL CHECK(testament in ('OLD', 'NEW'))
);
INSERT INTO books VALUES(1,'Genesis',50,'OLD');
INSERT INTO books VALUES(2,'Exodus',40,'OLD');
INSERT INTO books VALUES(3,'Leviticus',27,'OLD');
INSERT INTO books VALUES(4,'Numbers',36,'OLD');
INSERT INTO books VALUES(5,'Deuteronomy',34,'OLD');
INSERT INTO books VALUES(6,'Joshua',24,'OLD');
INSERT INTO books VALUES(7,'Judges',21,'OLD');
INSERT INTO books VALUES(8,'Ruth',4,'OLD');
INSERT INTO books VALUES(9,'1 Samuel',31,'OLD');
INSERT INTO books VALUES(10,'2 Samuel',24,'OLD');
INSERT INTO books VALUES(11,'1 Kings',22,'OLD');
INSERT INTO books VALUES(12,'2 Kings',25,'OLD');
INSERT INTO books VALUES(13,'1 Chronicles',29,'OLD');
INSERT INTO books VALUES(14,'2 Chronicles',36,'OLD');
INSERT INTO books VALUES(15,'Ezra',10,'OLD');
INSERT INTO books VALUES(16,'Nehemiah',13,'OLD');
INSERT INTO books VALUES(17,'Esther',10,'OLD');
INSERT INTO books VALUES(18,'Job',42,'OLD');
INSERT INTO books VALUES(19,'Psalms',150,'OLD');
INSERT INTO books VALUES(20,'Proverbs',31,'OLD');
INSERT INTO books VALUES(21,'Ecclesiastes',12,'OLD');
INSERT INTO books VALUES(22,'Song of Solomon',8,'OLD');
INSERT INTO books VALUES(23,'Isaiah',66,'OLD');
INSERT INTO books VALUES(24,'Jeremiah',52,'OLD');
INSERT INTO books VALUES(25,'Lamentations',5,'OLD');
INSERT INTO books VALUES(26,'Ezekiel',48,'OLD');
INSERT INTO books VALUES(27,'Daniel',12,'OLD');
INSERT INTO books VALUES(28,'Hosea',14,'OLD');
INSERT INTO books VALUES(29,'Joel',3,'OLD');
INSERT INTO books VALUES(30,'Amos',9,'OLD');
INSERT INTO books VALUES(31,'Obadiah',1,'OLD');
INSERT INTO books VALUES(32,'Jonah',4,'OLD');
INSERT INTO books VALUES(33,'Micah',7,'OLD');
INSERT INTO books VALUES(34,'Nahum',3,'OLD');
INSERT INTO books VALUES(35,'Habakkuk',3,'OLD');
INSERT INTO books VALUES(36,'Zephaniah',3,'OLD');
INSERT INTO books VALUES(37,'Haggai',2,'OLD');
INSERT INTO books VALUES(38,'Zechariah',14,'OLD');
INSERT INTO books VALUES(39,'Malachi',4,'OLD');
INSERT INTO books VALUES(40,'Matthew',28,'NEW');
INSERT INTO books VALUES(41,'Mark',16,'NEW');
INSERT INTO books VALUES(42,'Luke',24,'NEW');
INSERT INTO books VALUES(43,'John',21,'NEW');
INSERT INTO books VALUES(44,'Acts',28,'NEW');
INSERT INTO books VALUES(45,'Romans',16,'NEW');
INSERT INTO books VALUES(46,'1 Corinthians',16,'NEW');
INSERT INTO books VALUES(47,'2 Corinthians',13,'NEW');
INSERT INTO books VALUES(48,'Galatians',6,'NEW');
INSERT INTO books VALUES(49,'Ephesians',6,'NEW');
INSERT INTO books VALUES(50,'Philippians',4,'NEW');
INSERT INTO books VALUES(51,'Colossians',4,'NEW');
INSERT INTO books VALUES(52,'1 Thessalonians',5,'NEW');
INSERT INTO books VALUES(53,'2 Thessalonians',3,'NEW');
INSERT INTO books VALUES(54,'1 Timothy',6,'NEW');
INSERT INTO books VALUES(55,'2 Timothy',4,'NEW');
INSERT INTO books VALUES(56,'Titus',3,'NEW');
INSERT INTO books VALUES(57,'Philemon',1,'NEW');
INSERT INTO books VALUES(58,'Hebrews',13,'NEW');
INSERT INTO books VALUES(59,'James',5,'NEW');
INSERT INTO books VALUES(60,'1 Peter',5,'NEW');
INSERT INTO books VALUES(61,'2 Peter',3,'NEW');
INSERT INTO books VALUES(62,'1 John',5,'NEW');
INSERT INTO books VALUES(63,'2 John',1,'NEW');
INSERT INTO books VALUES(64,'3 John',1,'NEW');
INSERT INTO books VALUES(65,'Jude',1,'NEW');
INSERT INTO books VALUES(66,'Revelation',22,'NEW');

CREATE TABLE book_abbreviations(
    id INTEGER PRIMARY KEY NOT NULL,
    book_id INTEGER NOT NULL REFERENCES books(id),
    abbreviation TEXT NOT NULL
);
CREATE INDEX book_abbreviations_book_id_idx ON book_abbreviations(book_id);
CREATE INDEX book_abbreviations_abbreviation_idx ON book_abbreviations(abbreviation);

INSERT INTO book_abbreviations (book_id, abbreviation)
SELECT id, LOWER(name) FROM books;

INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (1,'gen');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (1,'ge');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (1,'gn');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (2,'ex');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (2,'exod');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (2,'exo');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (3,'lev');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (3,'le');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (3,'lv');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (4,'num');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (4,'nu');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (4,'nm');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (4,'nb');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (5,'deut');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (5,'de');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (5,'dt');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (6,'josh');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (6,'jos');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (6,'jsh');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (7,'judg');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (7,'jdg');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (7,'jg');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (7,'jdgs');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (8,'ruth');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (8,'rth');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (8,'ru');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (9,'1 sam');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (9,'1 sm');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (9,'1 sa');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (9,'1 s');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (9,'i sam');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (9,'i sa');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (9,'1sam');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (9,'1sa');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (9,'1s');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (9,'1st samuel');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (9,'1st sam');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (9,'first samuel');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (9,'first sam');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (10,'2 sam');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (10,'2 sm');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (10,'2 sa');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (10,'2 s');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (10,'ii sam');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (10,'ii sa');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (10,'2sam');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (10,'2sa');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (10,'2s');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (10,'2nd samuel');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (10,'2nd sam');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (10,'second samuel');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (10,'second sam');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (11,'1 kings');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (11,'1 kgs');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (11,'1 ki');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (11,'1kgs');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (11,'1kin');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (11,'1ki');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (11,'1k');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (11,'i kgs');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (11,'i ki');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (11,'1st kings');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (11,'1st kgs');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (11,'first kings');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (11,'first kgs');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (12,'2 kings');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (12,'2 kgs');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (12,'2 ki');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (12,'2kgs');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (12,'2kin');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (12,'2ki');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (12,'2k');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (12,'ii kgs');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (12,'ii ki');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (12,'2nd kings');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (12,'2nd kgs');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (12,'second kings');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (12,'second kgs');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (13,'1 chron');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (13,'1 chr');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (13,'1 ch');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (13,'1chron');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (13,'1chr');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (13,'1ch');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (13,'i chron');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (13,'i chr');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (13,'i ch');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (13,'1st chronicles');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (13,'1st chron');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (13,'first chronicles');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (13,'first chron');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (14,'2 chron');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (14,'2 chr');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (14,'2 ch');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (14,'2chron');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (14,'2chr');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (14,'2ch');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (14,'ii chron');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (14,'ii chr');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (14,'ii ch');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (14,'2nd chronicles');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (14,'2nd chron');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (14,'second chronicles');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (14,'second chron');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (15,'ezra');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (15,'ezr');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (15,'ez');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (16,'neh');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (16,'ne');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (17,'est');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (17,'esth');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (17,'es');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (18,'job');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (18,'jb');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (19,'ps');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (19,'psalm');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (19,'pslm');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (19,'psa');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (19,'psm');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (19,'pss');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (20,'prov');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (20,'pro');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (20,'prv');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (20,'pr');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (21,'eccles');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (21,'eccle');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (21,'ecc');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (21,'ec');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (21,'qoh');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (22,'song');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (22,'song of songs');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (22,'sos');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (22,'so');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (22,'canticle of canticles');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (22,'canticles');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (22,'cant');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (23,'isa');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (23,'is');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (24,'jer');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (24,'je');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (24,'jr');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (25,'lam');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (25,'la');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (26,'ezek');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (26,'eze');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (26,'ezk');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (27,'dan');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (27,'da');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (27,'dn');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (28,'hos');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (28,'ho');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (29,'jl');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (30,'am');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (31,'obad');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (31,'ob');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (32,'jnh');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (32,'jon');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (33,'mic');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (33,'mc');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (34,'nah');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (34,'na');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (35,'hab');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (35,'hb');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (36,'zeph');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (36,'zep');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (36,'zp');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (37,'hag');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (37,'hg');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (38,'zech');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (38,'zec');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (38,'zc');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (39,'mal');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (39,'ml');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (40,'matt');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (40,'mt');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (41,'mrk');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (41,'mar');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (41,'mk');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (41,'mr');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (42,'luk');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (42,'lk');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (43,'joh');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (43,'jhn');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (43,'jn');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (44,'act');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (44,'ac');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (45,'rom');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (45,'ro');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (45,'rm');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (46,'1 cor');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (46,'1 co');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (46,'i cor');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (46,'i co');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (46,'1cor');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (46,'1co');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (46,'i corinthians');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (46,'1corinthians');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (46,'1st corinthians');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (47,'2nd corinthians');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (47,'2 cor');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (47,'2 co');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (47,'ii cor');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (47,'ii co');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (47,'2cor');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (47,'2co');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (47,'ii corinthians');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (47,'2corinthians');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (47,'2nd corinthians');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (47,'second corinthians');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (48,'gal');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (48,'ga');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (49,'eph');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (49,'ephes');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (50,'phil');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (50,'php');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (50,'pp');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (51,'col');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (51,'co');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (52,'1 thess');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (52,'1 thes');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (52,'1 th');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (52,'i thessalonians');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (52,'i thess');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (52,'i thes');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (52,'i th');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (52,'1thessalonians');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (52,'1thess');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (52,'1thes');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (52,'1th');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (52,'1st thessalonians');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (52,'1st thess');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (52,'first thessalonians');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (52,'first thess');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (53,'2 thess');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (53,'2 thes2 th');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (53,'ii thessalonians');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (53,'ii thess');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (53,'ii thes');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (53,'ii th');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (53,'2thessalonians');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (53,'2thess');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (53,'2thes');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (53,'2th');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (53,'2nd thessalonians');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (53,'2nd thess');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (53,'second thessalonians');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (53,'second thess');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (54,'1 tim');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (54,'1 ti');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (54,'i timothy');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (54,'i tim');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (54,'i ti');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (54,'1timothy');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (54,'1tim');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (54,'1ti');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (54,'1st timothy');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (54,'1st tim');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (54,'first timothy');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (54,'first tim');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (55,'2 tim');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (55,'2 ti');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (55,'ii timothy');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (55,'ii tim');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (55,'ii ti');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (55,'2timothy');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (55,'2tim');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (55,'2ti');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (55,'2nd timothy');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (55,'2nd tim');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (55,'second timothy');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (55,'second tim');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (56,'titus');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (56,'tit');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (56,'ti');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (57,'philem');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (57,'phm');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (57,'pm');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (58,'heb');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (59,'jas');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (59,'jm');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (60,'1 pet');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (60,'1 pe');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (60,'1 pt');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (60,'1 p');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (60,'i pet');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (60,'i pt');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (60,'i pe');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (60,'1peter');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (60,'1pet');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (60,'1pe');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (60,'1pt');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (60,'1p');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (60,'i peter');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (60,'1st peter');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (60,'first peter');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (61,'2 pet');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (61,'2 pe');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (61,'2 pt');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (61,'2 p');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (61,'ii peter');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (61,'ii pet');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (61,'ii pt');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (61,'ii pe');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (61,'2peter');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (61,'2pet');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (61,'2pe');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (61,'2pt');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (61,'2p');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (61,'2nd peter');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (61,'second peter');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (62,'1 jhn');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (62,'1 jn');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (62,'1 j');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (62,'1john');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (62,'1jhn');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (62,'1joh');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (62,'1jn');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (62,'1jo');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (62,'1j');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (62,'i john');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (62,'i jhn');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (62,'i joh');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (62,'i jn');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (62,'i jo');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (62,'1st john');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (62,'first john');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (63,'2 jhn');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (63,'2 jn');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (63,'2 j');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (63,'2john');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (63,'2jhn');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (63,'2joh');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (63,'2jn');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (63,'2jo');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (63,'2j');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (63,'ii john');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (63,'ii jhn');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (63,'ii joh');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (63,'ii jn');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (63,'ii jo');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (63,'2nd john');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (63,'second john');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (64,'3 jhn');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (64,'3 jn');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (64,'3 j');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (64,'3john');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (64,'3jhn');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (64,'3joh');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (64,'3jn');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (64,'3jo');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (64,'3j');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (64,'iii john');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (64,'iii jhn');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (64,'iii joh');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (64,'iii jn');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (64,'iii jo');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (64,'3rd john');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (64,'third john');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (65,'jud');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (65,'jd');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (66,'rev');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (66,'re');
INSERT INTO book_abbreviations (book_id, abbreviation) VALUES (66,'the revelation');
