version: "3.8"

services:
  app:
    image: ghcr.io/dspeckhals/bible.rs:latest

  gateway:
    image: nginx:1.23.3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html:ro
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/dhparam.pem:/etc/ssl/certs/dhparam.pem:ro
      - certbot-etc:/etc/letsencrypt:ro
      - certbot-var:/var/lib/letsencrypt:ro
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - gateway
    command: certonly --webroot --webroot-path=/var/www/html --email ${LE_EMAIL} --agree-tos -n -d bible.rs

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: $PWD/web/dist/
      o: bind
