[package]
name = "db"
version = "0.1.0"
authors = ["Dustin Speckhals <dustin1114@gmail.com>"]
edition = "2018"

[dependencies.diesel]
version = "1.3.2"
default-features = false
features = ["sqlite", "r2d2"]

[dependencies.libsqlite3-sys]
version = ">=0.8.0, <0.10.0"
default-features = false
features = ["buildtime_bindgen"]

[dependencies]
diesel_migrations = "1.3.0"
env_logger = "0.6.0"
failure = "0.1.3"
lazy_static = "1.2.0"
regex = "1.1.0"
serde = "1.0.82"
serde_derive = "1.0.82"
