[package]
name = "db"
version = "0.1.0"
authors = ["Dustin Speckhals <dustin1114@gmail.com>"]
edition = "2018"

[dependencies.diesel]
version = "1.4.3"
default-features = false
features = ["sqlite", "r2d2"]

[dependencies.libsqlite3-sys]
version = ">=0.8.0, <0.17.0"
default-features = false
features = ["buildtime_bindgen"]

[dependencies]
diesel_migrations = "1.4.0"
env_logger = "0.7.1"
failure = "0.1.6"
lazy_static = "1.4.0"
regex = "1.3.1"
serde = "1.0.104"
serde_derive = "1.0.104"
