[package]
name = "db"
version = "0.1.0"
authors = ["Dustin Speckhals <dustin1114@gmail.com>"]
edition = "2018"

[dependencies.diesel]
version = "1.3.2"
default-features = false
features = ["sqlite", "r2d2"]

[dependencies]
diesel_migrations = "1.3.0"
env_logger = "0.5.13"
failure = "0.1.2"
lazy_static = "1.1.0"
regex = "1"
serde = "1.0.76"
serde_derive = "1.0.76"
