[package]
name = "sentry_actix"
version = "0.1.0"
authors = ["Dustin Speckhals <dustin1114@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "1.0.5"
futures = "0.1.28"
sentry = "0.17.0"
uuid = "0.7.4"
