name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  lint_test:
    name: Lint and Test
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Cache Cargo Registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache Cargo Index
        uses: actions/cache@v3
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache Cargo Build
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

      - name: Install SQLite Build and Binding Tools
        run: |
          sudo apt-get update
          sudo apt-get install autoconf curl gcc make tcl clang-14 libclang-14-dev llvm-14-dev

      - name: Build SQLite
        run: ./scripts/ci/install-sqlite.sh

      - name: Install Lint Tools
        run: |
          rustup component add rustfmt
          rustup component add clippy

      - name: Lint
        run: |
          cargo fmt -- --check
          cargo clippy --all-targets --all-features --all

      - name: Test
        run: |
          cargo build --all
          cargo test --all

