[package]
name = "web"
version = "0.1.0"
authors = ["Dustin Speckhals <dustin1114@gmail.com>"]
edition = "2018"

[dependencies.db]
path = "../db"

[dependencies.sentry_actix]
path = "../sentry_actix"

[dependencies]
actix-files = "0.2.1"
actix-rt = "1.1.1"
actix-web = "2.0.0"

dotenv = "0.15.0"
env_logger = "0.7.1"
failure = "0.1.8"
futures = "0.3.5"
handlebars = { version = "3.0.1", features = ["dir_source"] }
lazy_static = "1.4.0"
log = "0.4.8"
num_cpus = "1.13.0"
sentry = "0.18.1"
serde = "1.0.110"
serde_derive = "1.0.110"
serde_json = "1.0.53"
url = "2.1.1"
