[package]
name = "web"
version = "0.1.0"
authors = ["Dustin Speckhals <dustin1114@gmail.com>"]
edition = "2018"

[dependencies.db]
path = "../db"

[dependencies]
actix-web = "0.7.5"
dotenv = "0.13.0"
env_logger = "0.5.13"
failure = "0.1.2"
futures = "0.1.25"
handlebars = "1.0.3"
lazy_static = "1.1.0"
log = "0.4.5"
num_cpus = "1.8.0"
serde = "1.0.76"
serde_derive = "1.0.76"
serde_json = "1.0.26"
url = "1.7.1"
