[package]
name = "web"
version = "0.1.0"
authors = ["Dustin Speckhals <dustin1114@gmail.com>"]
edition = "2018"

[dependencies.db]
path = "../db"

[dependencies]
actix-files = "0.1.0-beta.1"
actix-web = "1.0.0-beta.2"

dotenv = "0.13.0"
env_logger = "0.5.13"
failure = "0.1.3"
futures = "0.1.25"
handlebars = "1.1.0"
lazy_static = "1.2.0"
log = "0.4.6"
num_cpus = "1.9.0"
serde = "1.0.82"
serde_derive = "1.0.82"
serde_json = "1.0.33"
url = "1.7.2"
