[package]
name = "web"
version = "0.1.0"
authors = ["Dustin Speckhals <dustin1114@gmail.com>"]
edition = "2018"

[dependencies.db]
path = "../db"

[dependencies.sentry_actix]
path = "../sentry_actix"

[dependencies]
actix-files = "0.1.4"
actix-web = "1.0.5"

dotenv = "0.14.1"
env_logger = "0.6.2"
failure = "0.1.5"
futures = "0.1.28"
handlebars = "2.0.1"
lazy_static = "1.4.0"
log = "0.4.8"
num_cpus = "1.10.1"
sentry = "0.17.0"
serde = "1.0.99"
serde_derive = "1.0.99"
serde_json = "1.0.40"
url = "1.7.2"
